-- View: qwat_od.vw_export_sia405pt_protection_tube

-- DROP VIEW qwat_od.vw_export_sia405pt_protection_tube;

CREATE OR REPLACE VIEW qwat_od.vw_export_sia405pt_protection_tube
 AS
 SELECT sia405pt_protection_tube.obj_id,
    sia405pt_protection_tube.name_number,
    sia405pt_protection_tube.material,
    sia405pt_protection_tube.nominal_diameter,
    sia405pt_protection_tube.outside_diameter,
    sia405pt_protection_tube.lenght,
    sia405pt_protection_tube.installation_year,
    sia405pt_protection_tube.horizontal_positioning,
    sia405pt_protection_tube.status,
    sia405pt_protection_tube.sur_plus_cover,
    sia405pt_protection_tube.condition,
    sia405pt_protection_tube.remark,
    sia405pt_protection_tube.last_modification,
    sia405pt_protection_tube.fk_dataowner,
    sia405pt_protection_tube.fk_provider,
    sia405pt_protection_tube.fk_owner,
    sia405pt_protection_tube.fk_pipe,
    sia405pt_protection_tube.fk_folder,
	material.code AS material_code,
	material.vsacode AS material_vsacode,
	material.value_en AS material_value_en,
	material.value_fr AS material_value_fr,
	material.value_it AS material_value_it,
	material.value_ro AS material_value_ro,
	material.abbr_en AS material_abbr_en,
	material.abbr_de AS material_abbr_de,
	material.abbr_fr AS material_abbr_fr,
	material.abbr_it AS material_abbr_it,
	material.abbr_ro AS material_abbr_ro,
	material.active AS material_active,
	horizontal_positioning.code AS horizontal_positioning_code,
	horizontal_positioning.vsacode AS horizontal_positioning_vsacode,
	horizontal_positioning.value_en AS horizontal_positioning_value_en,
	horizontal_positioning.value_fr AS horizontal_positioning_value_fr,
	horizontal_positioning.value_it AS horizontal_positioning_value_it,
	horizontal_positioning.value_ro AS horizontal_positioning_value_ro,
	horizontal_positioning.abbr_en AS horizontal_positioning_abbr_en,
	horizontal_positioning.abbr_de AS horizontal_positioning_abbr_de,
	horizontal_positioning.abbr_fr AS horizontal_positioning_abbr_fr,
	horizontal_positioning.abbr_it AS horizontal_positioning_abbr_it,
	horizontal_positioning.abbr_ro AS horizontal_positioning_abbr_ro,
	horizontal_positioning.active AS horizontal_positioning_active,
	status.code AS status_code,
	status.vsacode AS status_vsacode,
	status.value_en AS status_value_en,
	status.value_fr AS status_value_fr,
	status.value_it AS status_value_it,
	status.value_ro AS status_value_ro,
	status.abbr_en AS status_abbr_en,
	status.abbr_de AS status_abbr_de,
	status.abbr_fr AS status_abbr_fr,
	status.abbr_it AS status_abbr_it,
	status.abbr_ro AS status_abbr_ro,
	status.active AS status_active,
	dataowner.identifier AS dataowner_identifier,
	dataowner.identifier_short AS dataowner_identifier_short,
	dataowner.municipality_number AS dataowner_municipality_number,
	dataowner.organisation_type AS dataowner_organisation_type,
	dataowner.remark AS dataowner_remark,
	dataowner.status AS dataowner_status,
	dataowner.uid AS dataowner_uid,
	dataowner.last_modification AS dataowner_last_modification,
	provider.identifier AS provider_identifier,
	provider.identifier_short AS provider_identifier_short,
	provider.municipality_number AS provider_municipality_number,
	provider.organisation_type AS provider_organisation_type,
	provider.remark AS provider_remark,
	provider.status AS provider_status,
	provider.uid AS provider_uid,
	provider.last_modification AS provider_last_modification,
	owner.identifier AS owner_identifier,
	owner.identifier_short AS owner_identifier_short,
	owner.municipality_number AS owner_municipality_number,
	owner.organisation_type AS owner_organisation_type,
	owner.remark AS owner_remark,
	owner.status AS owner_status,
	owner.uid AS owner_uid,
	owner.last_modification AS owner_last_modification,
	folder.id AS id,
	folder.identification AS folder_identification,
	folder.description AS folder_description,
	folder.date_start AS folder_date_start,
	folder.date_end AS folder_date_end,
	folder.authority_approval_identification AS folder_authority_approval_identification,
	folder.authority_approval_description AS folder_authority_approval_description,
	folder.exported_to_authority AS folder_exported_to_authority,
	folder.export_remark AS folder_export_remark,
	folder.usr_annual_stats_flag AS folder_usr_annual_stats_flag
   FROM qwat_od.sia405pt_protection_tube
     LEFT JOIN qwat_vl.sia405pt_protection_tube_material material ON sia405pt_protection_tube.material = material.code
     LEFT JOIN qwat_vl.sia405pt_protection_tube_horizontal_positioning horizontal_positioning ON sia405pt_protection_tube.horizontal_positioning = horizontal_positioning.code
     LEFT JOIN qwat_vl.sia405pt_protection_tube_status status ON sia405pt_protection_tube.status = status.code
     LEFT JOIN qwat_od.organisation dataowner ON sia405pt_protection_tube.fk_dataowner = dataowner.obj_id
     LEFT JOIN qwat_od.organisation provider ON sia405pt_protection_tube.fk_provider = provider.obj_id
     LEFT JOIN qwat_od.organisation owner ON sia405pt_protection_tube.fk_owner = owner.obj_id
     LEFT JOIN qwat_od.folder folder ON sia405pt_protection_tube.fk_folder = folder.id;

ALTER TABLE qwat_od.vw_export_sia405pt_protection_tube
    OWNER TO sige;
