-- View: qwat_od.vw_export_sia405cc_cable

-- DROP VIEW qwat_od.vw_export_sia405cc_cable;

CREATE OR REPLACE VIEW qwat_od.vw_export_sia405cc_cable
 AS
 SELECT sia405cc_cable.obj_id,
    sia405cc_cable.name_number,
    sia405cc_cable.function,
    sia405cc_cable.cable_type,
    sia405cc_cable.horizontal_positioning,
    sia405cc_cable.status,
    sia405cc_cable.installation_year,
    sia405cc_cable.sur_plus_cover,
    sia405cc_cable.condition,
    sia405cc_cable.remark,
    sia405cc_cable.width,
    sia405cc_cable.elevation_determination,
    sia405cc_cable.depth,
    sia405cc_cable.last_modification,
    sia405cc_cable.fk_dataowner,
    sia405cc_cable.fk_provider,
    sia405cc_cable.fk_owner,
    sia405cc_cable.fk_folder,
	function.code AS function_code,
	function.vsacode AS function_vsacode,
	function.value_en AS function_value_en,
	function.value_fr AS function_value_fr,
	function.value_it AS function_value_it,
	function.value_ro AS function_value_ro,
	function.abbr_en AS function_abbr_en,
	function.abbr_de AS function_abbr_de,
	function.abbr_fr AS function_abbr_fr,
	function.abbr_it AS function_abbr_it,
	function.abbr_ro AS function_abbr_ro,
	function.active AS function_active,
	cable_type.code AS cable_type_code,
	cable_type.vsacode AS cable_type_vsacode,
	cable_type.value_en AS cable_type_value_en,
	cable_type.value_fr AS cable_type_value_fr,
	cable_type.value_it AS cable_type_value_it,
	cable_type.value_ro AS cable_type_value_ro,
	cable_type.abbr_en AS cable_type_abbr_en,
	cable_type.abbr_de AS cable_type_abbr_de,
	cable_type.abbr_fr AS cable_type_abbr_fr,
	cable_type.abbr_it AS cable_type_abbr_it,
	cable_type.abbr_ro AS cable_type_abbr_ro,
	cable_type.active AS cable_type_active,
	horizontal_positioning.code AS horizontal_positioning_code,
	horizontal_positioning.vsacode AS horizontal_positioning_vsacode,
	horizontal_positioning.value_en AS horizontal_positioning_value_en,
	horizontal_positioning.value_fr AS horizontal_positioning_value_fr,
	horizontal_positioning.value_it AS horizontal_positioning_value_it,
	horizontal_positioning.value_ro AS horizontal_positioning_value_ro,
	horizontal_positioning.abbr_en AS horizontal_positioning_abbr_en,
	horizontal_positioning.abbr_de AS horizontal_positioning_abbr_de,
	horizontal_positioning.abbr_fr AS horizontal_positioning_abbr_fr,
	horizontal_positioning.abbr_it AS horizontal_positioning_abbr_it,
	horizontal_positioning.abbr_ro AS horizontal_positioning_abbr_ro,
	horizontal_positioning.active AS horizontal_positioning_active,
	status.code AS status_code,
	status.vsacode AS status_vsacode,
	status.value_en AS status_value_en,
	status.value_fr AS status_value_fr,
	status.value_it AS status_value_it,
	status.value_ro AS status_value_ro,
	status.abbr_en AS status_abbr_en,
	status.abbr_de AS status_abbr_de,
	status.abbr_fr AS status_abbr_fr,
	status.abbr_it AS status_abbr_it,
	status.abbr_ro AS status_abbr_ro,
	status.active AS status_active,
	elevation_determination.code AS elevation_determination_code,
	elevation_determination.vsacode AS elevation_determination_vsacode,
	elevation_determination.value_en AS elevation_determination_value_en,
	elevation_determination.value_fr AS elevation_determination_value_fr,
	elevation_determination.value_it AS elevation_determination_value_it,
	elevation_determination.value_ro AS elevation_determination_value_ro,
	elevation_determination.abbr_en AS elevation_determination_abbr_en,
	elevation_determination.abbr_de AS elevation_determination_abbr_de,
	elevation_determination.abbr_fr AS elevation_determination_abbr_fr,
	elevation_determination.abbr_it AS elevation_determination_abbr_it,
	elevation_determination.abbr_ro AS elevation_determination_abbr_ro,
	elevation_determination.active AS elevation_determination_active,
	dataowner.identifier AS dataowner_identifier,
	dataowner.identifier_short AS dataowner_identifier_short,
	dataowner.municipality_number AS dataowner_municipality_number,
	dataowner.organisation_type AS dataowner_organisation_type,
	dataowner.remark AS dataowner_remark,
	dataowner.status AS dataowner_status,
	dataowner.uid AS dataowner_uid,
	dataowner.last_modification AS dataowner_last_modification,
	provider.identifier AS provider_identifier,
	provider.identifier_short AS provider_identifier_short,
	provider.municipality_number AS provider_municipality_number,
	provider.organisation_type AS provider_organisation_type,
	provider.remark AS provider_remark,
	provider.status AS provider_status,
	provider.uid AS provider_uid,
	provider.last_modification AS provider_last_modification,
	owner.identifier AS owner_identifier,
	owner.identifier_short AS owner_identifier_short,
	owner.municipality_number AS owner_municipality_number,
	owner.organisation_type AS owner_organisation_type,
	owner.remark AS owner_remark,
	owner.status AS owner_status,
	owner.uid AS owner_uid,
	owner.last_modification AS owner_last_modification,
	folder.id AS id,
	folder.identification AS folder_identification,
	folder.description AS folder_description,
	folder.date_start AS folder_date_start,
	folder.date_end AS folder_date_end,
	folder.authority_approval_identification AS folder_authority_approval_identification,
	folder.authority_approval_description AS folder_authority_approval_description,
	folder.exported_to_authority AS folder_exported_to_authority,
	folder.export_remark AS folder_export_remark,
	folder.usr_annual_stats_flag AS folder_usr_annual_stats_flag
   FROM qwat_od.sia405cc_cable
     LEFT JOIN qwat_vl.sia405cc_cable_function function ON sia405cc_cable.function = function.code
     LEFT JOIN qwat_vl.sia405cc_cable_cable_type cable_type ON sia405cc_cable.cable_type = cable_type.code
     LEFT JOIN qwat_vl.sia405cc_cable_horizontal_positioning horizontal_positioning ON sia405cc_cable.horizontal_positioning = horizontal_positioning.code
     LEFT JOIN qwat_vl.sia405cc_cable_status status ON sia405cc_cable.status = status.code
     LEFT JOIN qwat_vl.sia405cc_cable_elevation_determination elevation_determination ON sia405cc_cable.elevation_determination = elevation_determination.code
     LEFT JOIN qwat_od.organisation dataowner ON sia405cc_cable.fk_dataowner = dataowner.obj_id
     LEFT JOIN qwat_od.organisation provider ON sia405cc_cable.fk_provider = provider.obj_id
     LEFT JOIN qwat_od.organisation owner ON sia405cc_cable.fk_owner = owner.obj_id
     LEFT JOIN qwat_od.folder folder ON sia405cc_cable.fk_folder = folder.id;

ALTER TABLE qwat_od.vw_export_sia405cc_cable
    OWNER TO sige;
